ini_open("biorena_savedwavedata.ini")
inimodbohrok = ini_read_real("wavemodding","mod_bohrok_reset",5)
inimodinfected = ini_read_real("wavemodding","mod_infected_reset",4)
inimodrahkshi = ini_read_real("wavemodding","mod_rahkshi_reset",2)
inimodmakuta = ini_read_real("wavemodding","mod_makuta_reset",1)
ini_write_real("wavedata","bohrok",inimodbohrok)
ini_write_real("wavedata","infected",inimodinfected)
ini_write_real("wavedata","rahkshi",inimodrahkshi)
ini_write_real("wavedata","makuta",inimodmakuta)
ini_write_real("wavedata","bohrok_spawner",inimodbohrok)
ini_write_real("wavedata","infected_spawner",inimodinfected)
ini_write_real("wavedata","rahkshi_spawner",inimodrahkshi)
ini_write_real("wavedata","makuta_spawner",inimodmakuta)
ini_close()

